apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-api-service
  labels:
    app: kubernetes-demo-api
spec:
  selector:
    app: kubernetes-demo-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
